import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";
import React, { useState, useEffect } from "react";

function PostList({ data }) {
  const post = data.data;

  const [displayPosts, setDisplayPosts] = useState([]);

  useEffect(() => {
    const loadRelated = async () => {
      const response = await fetch(
        `https://hsi-sandbox.vercel.app/api/articles?categoryId=${post.category.id}&excludedArticleId=${post.id}`
      );
      const { data } = await response.json();

      setDisplayPosts(data.slice(0, 2));
    };

    loadRelated();
  }, []);

  return (
    <>
      <Head>
        <title>Ujian HSI Level 3</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <div className="body-header">
          <div className="container">
            <div className="page2-row-satu">
              <Link href="/">
                <Image
                  src="/logo.png"
                  width={99}
                  height={29}
                  alt="Picture of the author"
                />
              </Link>
            </div>{" "}
            <div className="page2-row-dua">
              <div className="">{post.title}</div>
            </div>{" "}
            <div className="page2-row-tiga">
              <div className="">{post.summary}</div>
            </div>{" "}
            <div className="page2-row-empat">
              {" "}
              <div>
                <span className="abu">By </span>
                <span className="hitam">
                  {post.author.firstName} {post.author.lastName}{" "}
                </span>
                <span className="abu">in</span>{" "}
                <span className="hitam">{post.category.name}</span>
              </div>
            </div>
          </div>
        </div>
        <div className="body-content">
          <div className="page2-row-lima">
            {" "}
            <div key={post.id}>
              <img className="card-2" src={post.thumbnail}></img>
            </div>
          </div>{" "}
          <div className="page2-row-enam">
            <div className="">{post.content}</div>
          </div>{" "}
          <div className="page2-row-tujuh">
            <div className="page2-row-tujuh-satu">You might also like...</div>
            <div className="page2-row-tujuh-dua">
              {" "}
              <Link
                href={{
                  pathname: "/[slug]/relates",
                  query: {},
                }}
                as={`/${post.slug}/relates`}
              >
                More
              </Link>
            </div>
          </div>
          <div className="page2-row-delapan">
            {displayPosts.map((relatedPost) => {
              return (
                <div>
                  {" "}
                  <div className="page2-row-delapan-satu">
                    <img src={relatedPost.thumbnail}></img>
                  </div>{" "}
                  <div className="page2-row-delapan-dua">
                    <span className="abu">By </span>
                    <span className="hitam">
                      {relatedPost.author.firstName}{" "}
                      {relatedPost.author.lastName}{" "}
                    </span>
                    <span className="abu">in</span>{" "}
                    <span className="hitam">{relatedPost.category.name}</span>
                  </div>{" "}
                  <div className="page2-row-delapan-tiga">
                    <div className="">{relatedPost.title}</div>
                  </div>{" "}
                  <div className="page2-row-delapan-empat">
                    <div className="">{relatedPost.summary}</div>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </main>
    </>
  );
}

export default PostList;

export async function getStaticProps(context) {
  const { params } = context;
  const response = await fetch(
    `https://hsi-sandbox.vercel.app/api/articles/${params.slug}`
  );

  const data = await response.json();

  return {
    props: {
      data,
    },
    revalidate: 10,
  };
}

export async function getStaticPaths() {
  const res = await fetch(`https://hsi-sandbox.vercel.app/api/articles`);
  const { meta } = await res.json();

  const { page, totalPages } = meta.pagination;

  let x = page;
  let data = [];
  while (x <= totalPages) {
    const response = await fetch(
      `https://hsi-sandbox.vercel.app/api/articles?page=${x}`
    );
    const y = await response.json();
    data = [...data, ...y.data];
    x++;
  }

  const paths = data.map((post) => {
    return {
      params: {
        slug: `${post.slug}`,
      },
    };
  });

  return {
    paths,
    fallback: false,
  };
}
