import Head from "next/head";
import Image from "next/image";
import React, { useState, useEffect } from "react";
import Link from "next/link";
import { useRouter } from "next/router";

function PostList({ meta, posts, dataID, categoryID, ID }) {
  const [displayPosts, setDisplayPosts] = useState(posts);
  const totalPage = meta.pagination.totalPages;
  const [pageSekarang, setPageSekarang] = useState(meta.pagination.page);

  const loadMore = async () => {
    setPageSekarang((pageSekarang) => pageSekarang + 1);

    const response = await fetch(
      `https://hsi-sandbox.vercel.app/api/articles?categoryId=${categoryID}&excludedArticleId=${ID}&page=${
        pageSekarang + 1
      }`
    );
    const { data } = await response.json();

    setDisplayPosts([...displayPosts, ...data]);
  };

  return (
    <>
      <Head>
        <title>Ujian HSI Level 3</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        {" "}
        <div className="body-header">
          <div className="container">
            <div className="page2-row-satu">
              {" "}
              <Link href="/">
                <Image
                  src="/logo.png"
                  width={99}
                  height={29}
                  alt="Picture of the author"
                />
              </Link>
            </div>{" "}
            <div className="page3-row-satu">Related Post List</div>
            <div className="page3-row-dua">
              <div className="page3-row-dua-satu">
                {" "}
                <img className="card-3" src={dataID.data.thumbnail}></img>
              </div>
              <div className="page3-row-dua-dua">
                <div className="page3-row-dua-dua-satu">
                  {dataID.data.title}
                </div>
                <div className="page3-row-dua-dua-dua">
                  {dataID.data.summary}
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="body-content">
          {displayPosts.map((post, index) => {
            return (
              <div key={post.id}>
                {" "}
                <div className="page3-row-tiga">
                  <div className="page3-row-tiga-satu">
                    <div className="page3-row-tiga-satu-satu">
                      {(index + 1).toString().padStart(2, "0")}
                    </div>
                    <div className="page3-row-tiga-satu-dua">{post.title}</div>
                    <div className="page3-row-tiga-satu-tiga">
                      {post.summary}
                    </div>
                  </div>
                  <div className="page3-row-tiga-dua">
                    <img className="card-3" src={post.thumbnail}></img>
                  </div>
                </div>
              </div>
            );
          })}
          <div className="row-tiga">
            {" "}
            <button
              onClick={loadMore}
              className={`btn-load-more ${
                pageSekarang === totalPage || totalPage === 0 ? "hidden" : ""
              }`}
              type="button"
            >
              Load More
            </button>
          </div>
        </div>
      </main>
    </>
  );
}

export default PostList;

export async function getServerSideProps(context) {
  const { resolvedUrl, query } = context;

  const cariID = await fetch(
    `https://hsi-sandbox.vercel.app/api/articles/${query.slug}`
  );

  const dataID = await cariID.json();
  const ID = dataID.data.id;
  const categoryID = dataID.data.category.id;

  const response = await fetch(
    `https://hsi-sandbox.vercel.app/api/articles?categoryId=${categoryID}&excludedArticleId=${ID}`
  );
  const { meta, data } = await response.json();

  return {
    props: {
      meta,
      posts: data,
      dataID,
      categoryID,
      ID,
    },
  };
}
